#!/usr/bin/env bash
# Auto-generated mapping from Infoblox provider .go files
declare -A RESOURCE_ATTRS

RESOURCE_ATTRS["infoblox_a_record"]=";"
RESOURCE_ATTRS["infoblox_aaaa_record"]=";"
RESOURCE_ATTRS["infoblox_alias_record"]=";"
RESOURCE_ATTRS["infoblox_cname_record"]=";"
RESOURCE_ATTRS["infoblox_dns_view"]=";"
RESOURCE_ATTRS["infoblox_dtc_lbdn"]=";"
RESOURCE_ATTRS["infoblox_dtc_pool"]=";"
RESOURCE_ATTRS["infoblox_dtc_server"]=";"
RESOURCE_ATTRS["infoblox_fixed_address"]=";"
RESOURCE_ATTRS["infoblox_ip_allocation"]=";"
RESOURCE_ATTRS["infoblox_ip_association"]=";"
RESOURCE_ATTRS["infoblox_ipv4_range_template"]=";"
RESOURCE_ATTRS["infoblox_ipv4_range"]=";"
RESOURCE_ATTRS["infoblox_ipv4_shared_network"]=";"
RESOURCE_ATTRS["infoblox_mx_record"]=";"
RESOURCE_ATTRS["infoblox_network_container"]=";"
RESOURCE_ATTRS["infoblox_network_view"]=";"
RESOURCE_ATTRS["infoblox_network"]=";"
RESOURCE_ATTRS["infoblox_ns_record"]=";"
RESOURCE_ATTRS["infoblox_ptr_record_expected_data_00"]=";"
RESOURCE_ATTRS["infoblox_ptr_record_expected_data_01"]=";"
RESOURCE_ATTRS["infoblox_ptr_record_test_data_00"]=";"
RESOURCE_ATTRS["infoblox_ptr_record_test_data_01"]=";"
RESOURCE_ATTRS["infoblox_ptr_record_test_err_data_00"]=";"
RESOURCE_ATTRS["infoblox_ptr_record"]=";"
RESOURCE_ATTRS["infoblox_srv_record"]=";"
RESOURCE_ATTRS["infoblox_txt_record"]=";"
RESOURCE_ATTRS["infoblox_zone_auth"]=";"
RESOURCE_ATTRS["infoblox_zone_delegated"]=";"
RESOURCE_ATTRS["infoblox_zone_forward"]=";"

